### ISSUE TITLE
Recent docker and CentOS 7 support

### ISSUE THREAD

**Issue by msciciel** [saltstack-formulas/docker-formula#109]
Hi,
I think that formula needs some corrections or rewrite to follow https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html and support recent versions of docker. Few changes are also required to support CentOS. If You agree I can provide pull request with newer version but it will break compatibility with old docker installations. I can also provide docker.v2 subformula pull request to support recents versions of docker on CentOS and Ubuntu. I could try to fix current code but it could hard or impossible to avoid compatibility issues.
I would be grateful if You could at least disagree with me. Formula in current state cannot be used with recent docker on CentOS 7. I'm open for discussion.

**Comment by blbradley** [comment]
Can you provide details of the errors you are getting on CentOS 7?

**Comment by msciciel** [comment]
Ofcourse I can provide details.

The first problem is that formula always enable old docker repository and it should be at least a option to disable this behavior. We are using red hat satellite/spacewalk for local mirroring of packages so we don't want to fetch packages from external mirrors. 

The second problem connected with first problem is that formula is using old repository and after release of docker community/enterprise edition new repository is under: https://download.docker.com/linux/centos/7/x86_64/stable/. 

The third problem is that formula is not working with new repository propably because of fact that docker-engine package was renamed to docker-ce:
```
----------
          ID: docker package
    Function: pkg.latest
        Name: docker-engine
      Result: False
     Comment: No information found for 'docker-engine'.
     Started: 09:35:06.809329
    Duration: 2603.389 ms
     Changes:   
----------
          ID: docker-service
    Function: service.running
        Name: docker
      Result: False
     Comment: One or more requisite failed: docker.docker package
     Started: 
    Duration: 
     Changes:   
```

The fourth problem for consideration is that in my opinion pkg.latest should not be the default state for package installation. Maybe it could be better to use pkg.installed and have a option to enable auto-update ?

**Comment by morsik** [comment]
I found that there is `lookup` for Docker package, far away from good Salt conventions:
```jinja
{% set pkg = salt['pillar.get']('docker-pkg:lookup', default={}, merge=True) %}
```

This should be inside `docker:lookup` called something like `name` or `pkg_name` or something similar like in other formulas like that.

**Comment by morsik** [comment]
Oh wait… this `pkg` is used nowhere!

**Comment by blbradley** [comment]
This formula does use Docker's upstream repo if you set the version pillar to a newer version.

This formula does not yet support the new style of CE/EE package names. This is true right now for any OS. We should leave this issue to that problem only. Please open up separate issues the other items.

I think this is a great time to talk about conventions. In an [exert from the linked page about MySQL Formula](https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#abstracting-static-defaults-into-a-lookup-table), it shows that formula using a `map.jinja`. However, in [mysql-formula], at this moment, there is no `map.jinja`. It uses a `defaults.yaml` and imports that across the formula. This poses a question: What is the convention?

SaltStack Inc has given the community a guide. But it is just that: a guide. The conventions depend on the people that maintain and submit to a particular formula.

@morsik `pkg` in `map.jinja` is merged into the defaults that are imported into other states. It is used for things like changing the `docker` Python package versions and configuring arguments to the Docker sysvinit or upstart service. You may think that it is used to change the package name, but that is not the case.

**Comment by msciciel** [comment]
If pkg name could be moved to map.jinja with ability to override it with pillar key similar to docker:lookup:pkg then it should work with docker community edition.

**Comment by blbradley** [comment]
Starting a new formula for Docker CE could be wise. Thoughts?

**Comment by myoung34** [comment]
out with the old in with the new

**Comment by morsik** [comment]
@blbradley: doesn't make any sence since Docker CE and old Docker all fully compatible with each other. They are have just different repos and names.

**Comment by blueyed** [comment]
Has anything happened with regard to supporting docker-ce from download.docker.com?
Looks like there should be something like `use_download_repo` (or `use_new(er)_repo`) with https://github.com/lock8/docker-formula/blob/f9ae050ec9792dedf2a8108c6df80c153545fd68/docker/init.sls#L19-L33.
