### ISSUE TITLE
Option for disabling repository configuration

### ISSUE THREAD

**Issue by msciciel** [saltstack-formulas/docker-formula#110]
Formula always enable docker repository and it should be at least a option to disable this behavior. We are using red hat satellite/spacewalk for local mirroring of packages so we don't want to fetch packages from external mirrors. Is it possible to add such feature to be configured via pillar ?

**Comment by blbradley** [comment]
It has been done in other formulas. See [this PR](https://github.com/saltstack-formulas/kibana-formula/pull/2) for details.

**Comment by msciciel** [comment]
May I provide PR for this feature ?

**Comment by blbradley** [comment]
Yes, please!
