### ISSUE TITLE
Manage registry service with salt.states.dockerio

### ISSUE THREAD

**Issue by cdarwin** [saltstack-formulas/docker-formula#12]
http://docs.saltstack.com/en/latest/ref/states/all/salt.states.dockerio.html

**Comment by nmadhok** [comment]
@cdarwin Good idea. Can you submit a Pull Request for this?

**Comment by cdarwin** [comment]
Yes, I created these issues to outline the I provements I intend to make. Feedback welcome.

**Comment by cdarwin** [comment]
I would like to table this improvement until the dockerio modules/states mature a bit. I will close the issue so there isn't an outstanding bug against the formula. I will leave my branch in the lucid repo to come back to later.
