### ISSUE TITLE
[Request for information] Why use this formula over saltstack docker modules?

### ISSUE THREAD

**Issue by dalvizu** [saltstack-formulas/docker-formula#131]
I'm looking to use docker to run a Jenkins server. I found that saltstack has It what looks to be native support for docker and docker-compose, handling both state and execution:

* https://docs.saltstack.com/en/latest/ref/states/all/salt.states.dockerng.html
* https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.dockercompose.html

It looks like docker-compose does not handle the installation, while this formula does.

Are there other advantages of using this over salt's support? Are there disadvantages? When would someone use this formula?

I'll happily add any answers to docs if that's helpful.

**Comment by blbradley** [comment]
Hello! Thank you for reaching out.

As a side note, what did you end up using?

**Comment by dalvizu** [comment]
I ended up using docker's support in saltstack and not use this formula. I handled installation of docker itself in my own salt code. Not sure if I did the right thing.

**Comment by blueyed** [comment]
@dalvizu 
Sounds good.
Installation of recent versions appears to still not be supported by this formula (https://github.com/saltstack-formulas/docker-formula/issues/109#issuecomment-361963900).

Can you share your code to install docker?
