### ISSUE TITLE
Using pip to install compose is not working

### ISSUE THREAD

**Issue by marty30** [saltstack-formulas/docker-formula#144]
Hi all,

I have had this issue for a while, but just ignored it. Whenever I run a salt highstate, I get the following failures:

> - - - - - - - - - -
>           ID: compose-pip
>     Function: pip.installed
>         Name: pip
>       Result: False
>      Comment: An importable pip module is required but could not be found on your system. 
> 	 This usually means that the system's pip package is not installed properly.
>      Started: 14:19:20.535905
>     Duration: 1.959 ms
>      Changes:
> - - - - - - - - - -
>           ID: compose
>     Function: pip.installed
>         Name: docker-compose
>       Result: False
>      Comment: An importable pip module is required but could not be found on your system. 
> 	 This usually means that the system's pip package is not installed properly.
>      Started: 14:19:20.538244
>     Duration: 1.47 ms
>      Changes:
> - - - - - - - - - -

Other issues suggested using reload_modules, but this is not part of the formula and it seems to work for others. Does anybody have an idea what might be the problem?

**Comment by noelmcloughlin** [comment]
I have not seen your specific issue. You should consider raising a Issue on salt for generic issues.

This [compose-pip state](https://github.com/saltstack-formulas/docker-formula/blob/821966747bf8e611f952d020a59a8cbf8a181e78/docker/compose.sls#L3) is an awkward implementation - installing `python-pip` is good practice on production systems, but adding `pip pip` on top of `python-pip` is asking for trouble IMHO.

I suspect your issue might go away if you remove the following lines from the salt formula(s) and run on fresh Linux OS.
```
  pip.installed:
    - name: pip
    - upgrade: True
```

**Comment by noelmcloughlin** [comment]
Resolved by #147 since this state no longer runs.
