### ISSUE TITLE
Exception raised when processing __virtual__ function for salt.loaded.int.utils.boto

### ISSUE THREAD

**Issue by plagov** [saltstack-formulas/docker-formula#161]
I started to use this formula recently and every time I run `state.apply` I get the following errors and warnings below. The `docker` state though is being executed properly and as expected but following messages are confusing.

And I've observed that state runs longer than it's expected. I don't have a proof that it happens because of this, but I might assume.

Salt version: `salt-minion 2018.3.2 (Oxygen)`
Python version: `Python 2.7.15rc1`

```
[ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.utils.boto. Module will not be loaded: 'module' object has no attribute '__version__'
[WARNING ] salt.loaded.int.utils.boto.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.utils.boto3. Module will not be loaded: 'module' object has no attribute '__version__'
[WARNING ] salt.loaded.int.utils.boto3.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto3', please fix this.
[WARNING ] /usr/lib/python2.7/dist-packages/salt/states/pkgrepo.py:313: DeprecationWarning: The 'refresh_db' argument to 'pkg.mod_repo' has been renamed to 'refresh'. Support for using 'refresh_db' will be removed in the Neon release of Salt.
```

Is it something with my environment or rather with a formula?

**Comment by noelmcloughlin** [comment]
The warnings can be ignored.  [see here also](https://github.com/saltstack/salt/issues/44062#issuecomment-365395131)

**Comment by plagov** [comment]
Ok, then I'll close this issue with the reference to a link from your comment.
