### ISSUE TITLE
docker_start_command is docker run

### ISSUE THREAD

**Issue by Poil** [saltstack-formulas/docker-formula#190]
Hi,

We use docker run in start command on systemd and other init system.
So it's working at the first run but if we don't use "remove_on_stop" option, at the second start we have an error because the container already exist.

Not sure if it's possible to check if the stopped container is the one we want or if we should force remove_on_stop at true

**Comment by Poil** [comment]
Also, I'm not sure `ExecStopPost=/usr/bin/docker rm -f` is a good solution, personally I would just append `--rm` to the ExecStart line

**Comment by Poil** [comment]
What do you think about this ?

**Comment by Poil** [comment]
https://github.com/saltstack/salt/issues/51023

**Comment by kjkeane** [comment]
Going to add to this, seeing the same issue.  But after reading the Docker documentation they even say in their "Use a process manager" [section](https://docs.docker.com/config/containers/start-containers-automatically/)
> To use a process manager, configure it to start your container or service using the same docker start or docker service command you would normally use to start the container manually. Consult the documentation for the specific process manager for more details.

**Comment by noelmcloughlin** [comment]
Fixed in merged #256
