### ISSUE TITLE
 Jinja variable 'config' is undefined

### ISSUE THREAD

**Issue by bluemalkin** [saltstack-formulas/docker-formula#224]
Hi,

I ran a state apply on this formula, docker dependencies got updated:
```
          ID: docker-package-dependencies
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: python3-pip
              The following packages were already installed: apt-transport-https, python3-apt
```

However it errors out with:
```
----------
          ID: docker-config
    Function: file.managed
        Name: /etc/default/docker
      Result: False
     Comment: Unable to manage file: Jinja variable 'config' is undefined
     Started: 05:20:04.208177
    Duration: 149.465 ms
     Changes:
----------
          ID: docker-service
    Function: service.running
        Name: docker
      Result: False
     Comment: One or more requisite failed: docker.install.docker-config
     Started: 05:20:04.359830
    Duration: 0.022 ms
     Changes:
```

Looking at the source code I cannot see anywhere where `config` is defined.

**Comment by myii** [comment]
@bluemalkin Just a quick response for the time being.  This is almost definitely related to the changes introduced in #216.  You'll also get a summary of the uses of `config` from this search:

* https://github.com/saltstack-formulas/docker-formula/search?utf8=%E2%9C%93&q=config&type=

It has been around in `defaults.yaml` for a while, it's just the usage probably requires a default value after #216.  Or you could try setting a default value of `[]` in your pillar.

**Comment by noelmcloughlin** [comment]
I replicated on Ubuntu.
```
          ID: docker-config
    Function: file.managed
        Name: /etc/default/docker
      Result: False
     Comment: Unable to manage file: Jinja variable 'config' is undefined
```

**Comment by myii** [comment]
@noelmcloughlin Thanks for confirming the regression.  Does the fix I suggested in https://github.com/saltstack-formulas/docker-formula/pull/216#issuecomment-513677832 work for you?

**Comment by noelmcloughlin** [comment]
> Thanks for confirming the regression. Does the fix I suggested in [#216 (comment)](https://github.com/saltstack-formulas/docker-formula/pull/216#issuecomment-513677832) work for you?

Both of the following work-

(1)
```
 58     - config:
 59       - config: {{ docker.config | d([]) }}
```

(2)
```
 58     - config:
 59       - config: {{ docker.config | json }}
```

This file is ignored by systemd btw #74

**Comment by myii** [comment]
@noelmcloughlin Shall we go with `| json` then?  Would you like to do it or shall I?  This fix is needed pretty quickly, to prevent other failures other there.

**Comment by noelmcloughlin** [comment]
Wait there is something wrong.  If you notice my comment above accidently used `config` parameter instead of `context` parameter.  Restesting both  `context:` parameter does not work.

`     Comment: Context must be formed as a dict`

I tried a few variations of `{{ docker.config | json}}' and '{{docker.config | d([]) }}' without success.

**Comment by noelmcloughlin** [comment]
>  58     - config:

The [example above](https://github.com/saltstack-formulas/docker-formula/issues/224#issuecomment-513887374)should have read ...

` 58 .   - context:`

**Comment by noelmcloughlin** [comment]
Got it.  Raised PR #226 @myii @bluemalkin

**Comment by myii** [comment]
@noelmcloughlin If you look at the example I gave earlier, it doesn't start with the leading hyphen -- that leads to it being evaluated as a list.

**Comment by noelmcloughlin** [comment]
Yes, I raised the fixed PR.

**Comment by bluemalkin** [comment]
Can confirm the fix works. Many thanks for the quick turnaround !
