### ISSUE TITLE
Support DOCKER_OPTS in pillar data

### ISSUE THREAD

**Issue by cdarwin** [saltstack-formulas/docker-formula#24]
As a systems administrator, I would like to adjust docker daemon startup arguments through a known interface.

In  Debian this is done through the file, `/etc/default/docker`. A list of options could be concatenated into an argument for [file.append](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.append) or something similar.

**Comment by tiadobatima** [comment]
Hi @cdarwin 

I submitted #40 to address this issue

Cheers,
g.

**Comment by cdarwin** [comment]
Thanks, @tiadobatima! :+1:
