### ISSUE TITLE
Can't manage /etc/docker/daemon.json using pillar syntax in v1.0.0

### ISSUE THREAD

**Issue by hkbakke** [saltstack-formulas/docker-formula#257]
I seems that docker-formula v1.0.0 lost its ability to manage /etc/docker/daemon.json. The file is included in a comment behind docker:pkg:docker:config_file in pillar.example, which leads me to believe that the intention is that I should give the config in docker:pkg:docker:config and set config_file to /etc/docker/daemon.json. However the template does not render json output as it is intended for rendering /etc/default/* files. It also adds a comment which is not allowed in json files.

Have I misunderstood something or is that feature gone?

**Comment by noelmcloughlin** [comment]
You could use that feature in v0.44.0 (https://github.com/saltstack-formulas/docker-formula/releases/tag/v0.44.0) until a PR is raised to fix this bug issue.

**Comment by arthurlogilab** [comment]
We'd be interrested in managing `/etc/docker/daemon.json` using this formula too

**Comment by noelmcloughlin** [comment]
Fixed in #282
