### ISSUE TITLE
Docker swarm creation

### ISSUE THREAD

**Issue by julienpaulino** [saltstack-formulas/docker-formula#271]
Hello,

Can you explain how do you create a docker swarm cluster using this formula?
Do I need to create an orchestration?

Thanks,

**Comment by noelmcloughlin** [comment]
Hey @julienpaulino 
The Swarm feature [exposes  Salt's Docker Swarm module, documented here](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.swarm.html) via YAML (`see pillar.example`). Please read that document carefully, then populate the required pillar data (see `pillar.example` also) and run `docker.swarm` states.  Swarm was added/merged during a recent formula refactoring but is not included in CI/CD so was "best effort" on my part.
https://github.com/saltstack-formulas/docker-formula/blob/648666d0590960f0f2a513c219ac7405bab62eb5/pillar.example#L170-L184

**Comment by noelmcloughlin** [comment]
Answered.
