### ISSUE TITLE
Compose.ng: Removed Container Remains

### ISSUE THREAD

**Issue by B1ue-W01f** [saltstack-formulas/docker-formula#278]
I believe currently, a container previously deployed through compose.ng, having been removed from the compose.ng pillar is not deleted but stays running on the host until removed manually. Should this be the correct workflow?

I would expect, not from a docker way of working as such but a saltstack / declarative way of working, that containers removed from the compose should be purged - or able to be enabled / disabled.

**Comment by noelmcloughlin** [comment]
#300
