### ISSUE TITLE
registry question

### ISSUE THREAD

**Issue by tiadobatima** [saltstack-formulas/docker-formula#38]
Hi guys,

I'm trying to understand the need for sqlalchemy in docker.registry.
Since the registry itself runs inside a container, I believe the sqlalchemy is already installed in the docker image. I'm not sure why sqlalchemy needs to be installed in the host level as well.
I'm bringing this up because the sqlalchemy requirement triggers to install a version of python2 that raises a bunch of package conflicts on ubuntu 14.04. Plus, if it's not needed, it's better if it's not there :)

Anything that I'm missing here?

Cheers,
g.

**Comment by iggy** [comment]
That state is a good example of formulas as a good starting point to base your own states off of... not so much of a plug and go/ready to run state.

I'm guessing that worked for someone else's needs and they decided to submit the change as-is.

**Comment by tiadobatima** [comment]
Thanks @iggy...
Yeah, after scouring the docs, I really can't see the requirement for sqlalchemy for the docker host.
Plus, the requirement for python2-formula for the registry state also seems superfluous, as the docker state and salt itself already provide python.
 
If there are no objections, I'm sending a PR to support registry 2.0, and I'll cleanup that bit

**Comment by iggy** [comment]
Do it in separate PRs if you don't mind.

**Comment by tiadobatima** [comment]
Not at all! Thanks @iggy.
