### ISSUE TITLE
private repository on docker hub?

### ISSUE THREAD

**Issue by sebest** [saltstack-formulas/docker-formula#47]
Hello,

Does it support private repository?

thanx

**Comment by sebest** [comment]
If so, how to enter credentials?

**Comment by ghostsquad** [comment]
`docker login` command would need to be run first, unfortunately, that saves those credentials in plain-text on the server, which is insecure. https://docs.docker.com/engine/reference/commandline/login/

You could easily do this with just a `cmd.run` state.
