### ISSUE TITLE
Limit scope of container install to specific minions

### ISSUE THREAD

**Issue by juwi** [saltstack-formulas/docker-formula#62]
Hi,

still fairly new to salt (just started using it, last friday), so please excuse if the answer to that one is actually obvious and I just can't see, yet.

Basically what I want to do is use this to start a swarm cluster. For this, I need to start a swarm master and several swarm minions. Is it possible to do this, with the current containers.sls formula? The way I understand it is, that it will iterate the containers containers on every node docker.containers gets applied to.

**Comment by gravyboat** [comment]
As far as I know this formula currently doesn't have support for Docker Swarm. If you feel like adding support for it that would be awesome!

**Comment by juwi** [comment]
Well, swarm is just another container to be started. Thats why I am asking if it is possible to assign containers to specific nodes, as swarm has two different roles, a master and workers. If there is a way to do this in the pillar, already, that would be great. Otherwise I'll have to think about something. 

But sure, It should be fairly easy to contribute this once it's finished.

**Comment by gravyboat** [comment]
Looking at the formula it doesn't currently appear to be configured in such a way. It's just to get docker itself configured and installed on systems. From there I imagine most people are writing additional states to handle their provisioning. You may want to simply add a `swarm.sls` that sets up the swarm container via values set in the pillar. Should be pretty easy to do.

**Comment by juwi** [comment]
Alright, thank you. Wasn't sure if there's already a way builtin or not. Looks like what you describe will be my way forward, then.

**Comment by gravyboat** [comment]
Sounds good! If you implement this please make a PR against the formula as I'm sure other users would benefit from the addition.

**Comment by gravyboat** [comment]
@juwi Oh I forgot, I made this project a while back if you need a place to get started in terms of spinning the container up: https://github.com/gravyboat/docka-docka-docka/blob/master/docka-salt/srv/salt/docker/docka.sls
