### ISSUE TITLE
On Debian Jessie it's not possible to install docker 1.10.2

### ISSUE THREAD

**Issue by bogdanr** [saltstack-formulas/docker-formula#69]
The formula doesn't allow the usage of https://apt.dockerproject.org/repo if Jessie is detected with oscodename thus it's not possible to install anything else besides Docker 1.6.

**Comment by gravyboat** [comment]
Closing thanks to #70

**Comment by tedski** [comment]
@gravyboat reopened by mistake?

**Comment by gravyboat** [comment]
Yeah sorry, the "closed" label didn't hit since I already had this page open.
