### ISSUE TITLE
version pillar should not be required

### ISSUE THREAD

**Issue by timwhite** [saltstack-formulas/docker-formula#81]
Having to specify an exact version string is a bit clunky. This is related to #80 as it would be nice to not have to specify a version at all, and just get the latest in a repository. I'm guessing you want to specify a version when using the docker repo's as they release versions so often. It just makes it hard to get started with this formula when specifying no version prevents you from using it due to systemd, and when specifying a version, you have to specify the exact version string of the package.

Even being able to do something like "1.11.*" would be nicer so we can have minor updates automatically but not major.

**Comment by colegatron** [comment]
If you don't specify version (comment out it on the pillar) it will take the latest version from the repo.
Just installed 1.12.1.

**Comment by hemebond** [comment]
If you don't specify a version you get a broken install on you can't interact with on Debian Jessie. I expected the default behaviour to follow the official Docker install guide.

**Comment by blbradley** [comment]
Support on Debian Jessie is definitely broken. I've started the discussion to fix it in #75.

**Comment by blbradley** [comment]
@hemebond I am getting the behavior you described. You are correct that something wrong with the logic there.

**Comment by blbradley** [comment]
@timwhite I'm going to rename this '

**Comment by blbradley** [comment]
@timwhite I agree that requiring version via pillar is not wise. I was able to use a wildcard with one of the repos that get configured but don't remember which. I'm going to change this title to reflect that requiring a version is the problem.

**Comment by blbradley** [comment]
@timwhite This issue is fixed. And you should be able to use a wildcard version in certain cases.

Closed in #93.
