### ISSUE TITLE
docker.containers fails to correctly start and manage containers (Start/Stop loop)

### ISSUE THREAD

**Issue by timwhite** [saltstack-formulas/docker-formula#82]
I believe we are hitting the issue with systemd managing the client, not containers. http://container-solutions.com/running-docker-containers-with-systemd/
The main docker issue is https://github.com/docker/docker/issues/6791
A possible solution is https://github.com/ibuildthecloud/systemd-docker

OS: Debian Jessie
Docker version 1.11.1, build 5604cbe

Basically, https://github.com/saltstack-formulas/docker-formula/blob/master/docker/files/systemd.conf#L22 starts with ```ExecStart=/usr/bin/docker run -d``` which tells docker to start the container in the background and then exit. So the docker client does that. Systemd thinks that docker "crashed" so tries to restart it (after running the ExecStop commands that pull down the running container). And the cycle starts again until the retry limit.

Removing the -d works, as then the client doesn't exit once the container has started, but as others have pointed out in the above links, this means systemd is managing the client, not the container, and in some situations this will cause a correctly running container to be restarted.

**Comment by tiadobatima** [comment]
I created #87 to address this
