### ISSUE TITLE
Use refresh_repo only for latest version?

### ISSUE THREAD

**Issue by blueyed** [saltstack-formulas/docker-formula#85]
The `docker.refresh_repo` setting (defaulting to `True`) gets used for `pkg.installed`.

This causes `apt-get update` to run always.

But when specifying a specific version this could be skipped?!  (since the repo gets updated through `pkgrepo` already in case it gets added)

**Comment by ticosax** [comment]
When one wants to bump the version of docker, `apt-get update` needs to be executed first. In order to let the system know where to fetch the new desired version.
Ideally, we should refresh the repo on sls `changed` event. But this is not a supported feature of saltstack IMO.

**Comment by blueyed** [comment]
I've thought that `pkgrepo.managed` would trigger the `apt-get update` (in case the repo is changed for a newer version).
If the repo does not change because of a new version, then the new version should be known already.
Also the first `pkg.installed` would run `apt-get update` already (with `refresh` unset).

**Comment by ticosax** [comment]
> I've thought that pkgrepo.managed would trigger the apt-get update (in case the repo is changed for a newer version).

Unfortunately not, because state executions are stateless, they are not aware of previous 
configuration.

> If the repo does not change because of a new version, then the new version should be known already.

Only if another `state` requires `pkg.upgrade` which is not always the case.

> Also the first pkg.installed would run apt-get update already (with refresh unset).

salt doens't know when it run for the first time. 

I'm afraid we will have to stick to it.

**Comment by blbradley** [comment]
@blueyed Is this still an issue for you?

**Comment by noelmcloughlin** [comment]
Fixed in merged #256
