### ISSUE TITLE
script does not seem to work on ubuntu xenial

### ISSUE THREAD

**Issue by quorak** [saltstack-formulas/docker-formula#90]
hey there,

great work. I was using this script for quite a while on ubuntu trusty. Now, having some vm's on ubuntu 16.04 LTS (xenial) the formular doesn't seem to work out of the box.

The script hangs forever on the master. And wenn I look into the apt-get log files on the minion (with `sudo tail -f -n 1000 /var/log/apt/term.log`), I see it stucked at the following line:

```
Setting up docker-engine (1.12.2-0~xenial) ...

Configuration file '/etc/default/docker'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
 ==> Keeping old config file as default.
```

hope this helps you guys.

**Comment by redundancydisorder** [comment]
Not completely the issue but the permissions on the systemd service file should be 644 not 700. as set in containers.sls. I don't have a completed fix but I am working on it. If I figure it out I will update.

**Comment by blbradley** [comment]
@quorak Can you show your pillar data?

It looks as if this may have happened when you were switching between Docker versions by changing the version pillar. Is that correct?

**Comment by blbradley** [comment]
@quorak Can you try the latest master and report back?

**Comment by tyhunt99** [comment]
I am seeing a similar issue. Docker is being installed and running properly. But 16.04 is now running systemd so the /etc/default/docker does not do anything on systems running systemd. This means my docker opts are all getting ignored.

**Comment by blbradley** [comment]
@tyhunt99 You can use a systemd drop in to override unit files.

**Comment by tyhunt99** [comment]
@blbradley ah okay thank you

**Comment by blbradley** [comment]
@tyhunt99 No problem. I just found out about them last week. They are great!

**Comment by quorak** [comment]
I switched back using the docker installation provided by the default repositories.
We can close this issue, if you can't reproduce it. best

**Comment by blbradley** [comment]
@quorak I'll gladly help you with any issue with this formula.

Not closing until 16.06 covered under the test suite.
