### ISSUE TITLE
Test suite optimization

### ISSUE THREAD

**Issue by blbradley** [saltstack-formulas/docker-formula#95]
[Last test run](https://travis-ci.org/saltstack-formulas/docker-formula/builds/177769754) took over 30 minutes. We need better Docker images to solve this.

@gravyboat @whiteinge Either of you know what the status of SaltStack's Docker Hub is? It definitely lacks images of more modern OSes needed for this. Nice to see some tooling in this regard! 😁

**Comment by whiteinge** [comment]
I don't know much about that repo but I asked around. Nobody here is actively maintaining it. Those images were originally created for the main Salt test suite but we're not using Docker there anymore. We'll gladly take contributions to the repo, of course! But since we don't have an immediate need for those images it doesn't look like we're likely to throw any company time at it in the near term.

**Comment by blbradley** [comment]
@whiteinge I've had some time to think. Would it be better to create a new repo for community formula testing or contribute to [the SaltStack docker container repo](https://github.com/saltstack/docker-containers)?

**Comment by whiteinge** [comment]
I think that answer is whichever the people putting in the work feel most comfortable with and is most effective. It would make a lot of sense to open that repo up to contributors, same as here with the formulas org, so contributors just have full access to get stuff done. If that sounds interesting to you I'll happily configure that repo and get you added.

**Comment by blbradley** [comment]
Thanks for you input, Seth!

I think, regarding separation of concerns, testing SaltStack and testing formulas will need individual repos. Formula testing could extend to multiple stable versions of SaltStack while testing SaltStack could focus on the develop version. Individual repos will also give you less administrative work to do if the new repo is put under the formulas org. I like giving you less administrative work!

**Comment by blbradley** [comment]
How is this?

https://github.com/saltstack-formulas/docker-images

**Comment by blbradley** [comment]
Another repo does give the issue of: Where does it go on Docker Hub? I doubt the 'saltstack-formulas' username is taken. The company can make the account, or I could make the account and transfer.

**Comment by whiteinge** [comment]
That sounds like a good plan to me. Feel free to make the account and ping me if I can do anything to help.

**Comment by blbradley** [comment]
[Organization](https://hub.docker.com/r/saltstackformulas/) has been created. Usernames on Docker Hub only allow alphanumeric strings and no symbols.

Initial results are good. Just need a good naming scheme.

**Comment by noelmcloughlin** [comment]
Fixed in merged #256
