### ISSUE TITLE
Docker compose requires separate install

### ISSUE THREAD

**Issue by ghostsquad** [saltstack-formulas/docker-formula#97]
Docker-compose is bundled with Docker on Mac and Windows, but requires a separate install on other OSs (like Ubuntu). I don't see anywhere in the README or `pillar.example` about installing `docker-compose`.

**Comment by ghostsquad** [comment]
Seems like the documentation is just a little out-of-date. I didn't put 1-1 together that simply requiring `docker.compose` in my states/formulas top.sls was enough to install it.

**Comment by blbradley** [comment]
@ghostsquad I could see your confusion since the docs don't say anything about installing docker compose. It uses 'Adds support for'. If you want to change the language there to be more clear, feel free to send a PR. I'll be happy to review.
