### ISSUE TITLE
Stopping a container should not remove it

### ISSUE THREAD

**Issue by ghostsquad** [saltstack-formulas/docker-formula#99]
I read this line, and was a little surprised by it.
https://github.com/saltstack-formulas/docker-formula/blob/master/docker/files/systemd.conf#L24

`ExecStopPost=/usr/bin/docker rm -f {{ name }}`

For the most part, docker containers should be stateless, but that's not always the case. I think this should be configurable.

**Comment by ernstae** [comment]
This is a "Me too, I agree"

**Comment by puneetk** [comment]
Nice change , thank you for keeping it configurable.
